import type { Metadata } from "next";
import "./globals.css";
import TopNav from "./components/topnav";
import BottomNav from "./components/bottomnav";

export const metadata: Metadata = {
  title: "Shajahan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <TopNav/>
        {children}
        <BottomNav/>
      </body>
    </html>
  );
}
