import type { Metadata } from "next";
import "./globals.css";
import TopNav from "./components/topnav";

export const metadata: Metadata = {
  title: "Shajahan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="h-screen w-screen"
      >
        <div className="h-[10%]">
        <TopNav/>
        </div>
        <div className="h-[90%]">
        {children}
        </div>
        
      </body>
    </html>
  );
}
