name: Build Container

on :
    workflow_dispatch:
        inputs:
            version:
                description: "Version update"
                required: true

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - name: Install dependencies
              run: npm install
            - name: Build App
              run: npm run build
