name: Hello World

on :
    workflow_dispatch:
        inputs:
            version:
                description: "Version update"
                required: true

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World"
            - name: print version
              run: echo "${{ github.event.inputs.version }}"