name: Build Container

on :
    workflow_dispatch:
        inputs:
            version:
                description: "Version update"
                required: true

jobs: 
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out
              uses: actions/checkout@v2
            
            - name: Set Up
              run: |
                git config --global user.name "shajahansheik"
                git config --global user.email "shajahan.j2se@gmail.com"
              
            - name: Bump Version
              id: bump-version
              run: |
                npm version patch
                curr_version=$(node -p "require('./package.json').version")
                echo "Current version: $curr_version"
                git push https://${{secrets.MY_PAT_TOKEN}}@github.com/shajahansheik/portfolio
                echo "Version updated to $curr_version"
