name: Build Container

on :
    push:
        branches:
            - main

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v2
            - name: bump version
              run: |
                npm version patch -m "bump version to %s"
                git push origin main --tags
            
